version: '3'

services:
    db:
        image: postgres
    web:
        build: containers/web_do_paulo
        volumes:
            - ./app:/code
        ports:
            - "5000:5000"
        depends_on:
            - db
